version: '3.8'

services:
  db:
    image: postgres:15
    container_name: asyncpayments-db
    environment:
      POSTGRES_DB: asyncpayments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passwordtest
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - railway_volume:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: asyncpayments-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/asyncpayments
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: passwordtest
      JWT_SECRET_KEY: super-secret-key-12345
      JWT_EXPIRATION: 86400000
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always

volumes:
  railway_volume: